//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightScheduleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightScheduleDetail()
        {
            this.TicketDetails = new HashSet<TicketDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime JourneyDate { get; set; }
        public decimal Price { get; set; }
        public int SeatAvailability { get; set; }
        public int FlightDetailId { get; set; }
    
        public virtual FlightDetail FlightDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketDetail> TicketDetails { get; set; }
    }
}
